# Generated by Django 5.2.5 on 2025-09-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telephone',
        ),
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre'),
        ),
    ]
