# Generated by Django 5.2.5 on 2025-12-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examenes', '0003_paei'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='estado',
            field=models.CharField(choices=[('realizado', 'Realizado'), ('pendiente', 'Pendiente'), ('desactualizado', 'Desactualizado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='paei',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado'), ('desactualizado', 'Desactualizado')], default='pendiente', max_length=20),
        ),
    ]
