# Generated by Django 5.2.5 on 2025-11-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdAlumno', models.CharField(help_text='Identificador institucional del alumno.', max_length=20, unique=True, verbose_name='ID del Alumno')),
                ('NombreAlumno', models.CharField(max_length=100)),
                ('ApellidoAlumno', models.CharField(max_length=100)),
                ('EdadAlumno', models.PositiveIntegerField()),
                ('EncargadoAlumno', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['ApellidoAlumno', 'NombreAlumno'],
            },
        ),
        migrations.CreateModel(
            name='AreaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Área del Personal',
                'verbose_name_plural': 'Áreas del Personal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdPersonal', models.CharField(help_text='Código institucional del miembro del personal.', max_length=20, unique=True, verbose_name='ID del Personal')),
                ('NombrePersonal', models.CharField(max_length=100)),
                ('ApellidoPersonal', models.CharField(max_length=100)),
                ('AreaPersonal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='registro.areapersonal', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Miembro del Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['ApellidoPersonal', 'NombrePersonal'],
            },
        ),
    ]
