# Generated by Django 5.2.5 on 2025-11-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='Activo',
            field=models.BooleanField(default=True, help_text='Indica si el alumno está activo en la institución.', verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='personal',
            name='Activo',
            field=models.BooleanField(default=True, help_text='Indica si el miembro del personal sigue prestando servicio.', verbose_name='¿Activo?'),
        ),
    ]
